### PR TITLE
Removing deprecated staging module and adding proxy support

### PR DESCRIPTION
**Pull request by bt-lemery**

### CODE REVIEW

**Comment by joshbeard** [comment]
I appreciate this, and apologize for the late response.

What do you think about a different name for the parameter that is more specific - to indicate it's for the download? There's a 'proxy' parameter already that is for the server configuration. Maybe something like `download_proxy_server`, `archive_proxy_server`, or `source_proxy_server`?

Also, if you wouldn't mind adding it to the `README`, that'd be great.

**Comment by bt-lemery** [comment]
No problem.  Updated.  LMK what you think.

**Comment by joshbeard** [comment]
I made some minor modifications to this, merged it to master, and published version 3.6.0 to the Puppet Forge: https://forge.puppet.com/joshbeard/bamboo/3.6.0/

You can see the differences here: https://github.com/bt-lemery/puppet-bamboo/compare/feature/migrating_to_archive_module...joshbeard:master

I did end up renaming the `download_proxy_server` to `proxy_server` like you originally had to be consistent with the other Atlassian modules.

Changes on top of your work:
* Minor test adjustments
* Update fixtures to source 'archive' module
* Update metadata to list 'archive' module dependency
* Lint fixes
* Add additional `proxy_type` parameter
* Fix Exec resource that stops service on upgrade - it had the archive resource for 'require' and 'before' (conflicting). 
* Unrelated adjustment to refresh systemd on service changes

**Comment by joshbeard** [comment]
Thank you for your contribution!

**Comment by bt-lemery** [comment]
And thank you!

**Pull request closed without merging**
